### PR TITLE
Remove / prefix from vhost when parsing

### PR DESCRIPTION
**Pull request by tyilo**
See https://www.rabbitmq.com/uri-spec.html

### CODE REVIEW

**Comment by gftea** [comment]
@tyilo thanks for your contribution. Please check and fix the CI error

**Comment by tyilo** [comment]
I haven't touched the lines it complains about.

Also, I wouldn't know how to fix https://github.com/gftea/amqprs/actions/runs/5666704166/job/15361926189?pr=104

**Comment by gftea** [comment]
you can fix the clippy error in ci/builds, the codecov error is not related to your change

**Comment by tyilo** [comment]
@gftea should be fixed now.

**Pull request merged**
