### PR TITLE
Setup TLS adaptor when parsing an amqprs uri

### PR DESCRIPTION
**Pull request by tyilo**

### CODE REVIEW

**Comment by tyilo** [comment]
@gftea Everything should be working now, but the CI still fails. I can't reproduce it locally.

**Comment by gftea** [comment]
@tyilo it seems about feature flag , the test is expecting w/o tls, but still tls is used 
```
api::connection::tests::test_amqps_scheme_without_tls stdout ----
thread 'api::connection::tests::test_amqps_scheme_without_tls' panicked at amqprs/src/api/connection.rs:1515:39:
called `Result::unwrap()` on an `Err` value: NetworkError("network io error: invalid peer certificate contents: invalid peer certificate: UnknownIssuer")
note: panic did not contain expected string
      panic message: `"called `Result::unwrap()` on an `Err` value: NetworkError(\"network io error: invalid peer certificate contents: invalid peer certificate: UnknownIssuer\")"`,
 expected substring: `"UriError"`
```

**Comment by gftea** [comment]
@tyilo I have rerun main branch, it works.
Try to reproduce it by run `cargo test --all-features --release`

**Comment by tyilo** [comment]
@gftea Ah I understand now, I didn't have the RabbitMQ server running.

I see two possible solutions:
- Remove the `test_amqps_scheme_without_tls` test
- Keep the `test_amqps_scheme_without_tls` test, but change the signature of `OpenConnectionArguments::tls_adaptor` to take a `Option<TlsAdaptor>` instead of `TlsAdaptor`, so that the test can explicitly disable the default TLS adaptor.

What do you prefer?

**Comment by gftea** [comment]
@tyilo , the failure of the test is user giving a `amqps` scheme which means it want to enable secure channel, but without tls adaptor, I think it prevents the incorrect  configuration from beginning, which is good thing

**Comment by tyilo** [comment]
> @tyilo , the test is prevent user giving a `amqps` scheme (implies secure channel) but without tls adaptor enabled. it prevents the incorrect configuration from beginning

I understand what the test does. However, it is no longer possible to create a configuration from an `amqps` url without a TLS adaptor.

So do we want to:
1. remove the test, or
2. allow setting no TLS adaptor for an `amqps` URL

I don't really have a strong opinion about what to do. What do you prefer?

**Comment by so-schen** [comment]
I see, this PR implicitly setup an adaptor without client authentication if amqps scheme used, how user can use amqps with its customized adapter?

**Comment by tyilo** [comment]
> I see, this PR implicitly setup an adaptor without client authentication if amqps scheme. HOW user can use amqps with its customized adapter?

You then call `tls_adaptor(...)` as before to override the default adaptor.

The default should be without client authentication as this is the default for other AMQP libraries (and clients using TLS in general).

**Comment by gftea** [comment]
Ok, let’s remove this test case as you suggested. Please help add documentation about the default behavior and how to customize it

**Review by gftea — APPROVED** [review]

**Pull request merged**
