### PR TITLE
Squash a several compiler warnings

### PR DESCRIPTION
**Pull request by michaelklishin**
References #87.

### CODE REVIEW

**Comment by michaelklishin** [comment]
@gftea I refactored a couple of places to use a `while let` loop. In the process we lose a tracing message for unsuccessful awaits on a (Rust) channel. I don't feel strongly about this but the value of those lines seemed insignificant to me, so I removed them.

**Comment by gftea** [comment]
Hi, When while loop exists, we still can log the message , it's a good message for troubleshooting

**Comment by gftea** [comment]
I remember Our test do use those functions, when test build with all features, where you see those warnings?

**Comment by michaelklishin** [comment]
I get them with `cargo build` in a clean repo on Rust nightly (1.70).

**Comment by michaelklishin** [comment]
This is not relevant for cases where the library is compiled with `--all-features`. Fair enough.

**Pull request closed without merging**
